services:

  app1-service:
    image: ghcr.io/thorsten-l/l9g-oidc-info:latest
    container_name: app1-service
    hostname: app1-service.dev.sonia.de
    restart: unless-stopped
    volumes:
      - ./data/global/app1/config.yaml:/workspace/config.yaml
      - ./certs/dev.sonia.de/server.p12:/workspace/server.p12
    environment:
      - TZ=Europe/Berlin
    ports:
      - "40443:40443"

networks:
  default:
    name: fop
    external: true
